// swift-tools-version:5.5
// The swift-tools-version declares the minimum version of Swift required to build this package.
// Don't modify - is Autogenerated

import PackageDescription

let package = Package(
    name: "GoogleMapsSP",
    products: [
        .library(
            name: "GoogleMaps",
            targets: [
                "GoogleMaps",
                "GoogleMapsBase",
                "GoogleMapsCore",
            ]
        ),
        .library(
            name: "GoogleMapsBase",
            targets: ["GoogleMapsBase"]
        ),
        .library(
            name: "GoogleMapsCore",
            targets: ["GoogleMapsCore"]
        ),
        .library(
            name: "GoogleMapsM4B",
            targets: ["GoogleMapsM4B"]
        ),
        .library(
            name: "GooglePlaces",
            targets: [
                "GooglePlaces",
                "GoogleMapsBase",
            ]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "GoogleMaps",
            url: "https://github.com/everli/GoogleMaps-SP-iOS/releases/download/6.0.1-maps/GoogleMaps.xcframework.zip",
            checksum: "16a389e375f3ff7e71d4f12b2d3851946215b0a12b4a8d1006b9d52070366966"
        ),
        .binaryTarget(
            name: "GoogleMapsBase",
            url: "https://github.com/everli/GoogleMaps-SP-iOS/releases/download/6.0.1-maps/GoogleMapsBase.xcframework.zip",
            checksum: "d296c2b1e82dab82b2a55caad0ee5f9a99097779bac08ad884f4a36dce72b9a1"
        ),
        .binaryTarget(
            name: "GoogleMapsCore",
            url: "https://github.com/everli/GoogleMaps-SP-iOS/releases/download/6.0.1-maps/GoogleMapsCore.xcframework.zip",
            checksum: "829cfc8f311025fd643ae24770983ceb61307a1b2787cbb20ebaac1d911bed7e"
        ),
        .binaryTarget(
            name: "GoogleMapsM4B",
            url: "https://github.com/everli/GoogleMaps-SP-iOS/releases/download/6.0.1-maps/GoogleMapsM4B.xcframework.zip",
            checksum: "3f5373d00b1008e3096fa801fcb68c37fbf2fe35ea491480cc750d13a7234895"
        ),
        .binaryTarget(
            name: "GooglePlaces",
            url: "https://github.com/everli/GoogleMaps-SP-iOS/releases/download/6.0.1-maps/GooglePlaces.xcframework.zip",
            checksum: "3b1bac13ceef6e249f213000849a2451b285d77697534e10f1a9f0474bf6a898"
        ),
    ]
)
